import { afterEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { ReviewRunPage } from "./ReviewRunPage";
import { ToastProvider } from "../components/ToastProvider";
import { installFetchMock } from "../test/mockFetch";
import { makeRunDetail } from "../test/fixtures";
import type { RunDetail } from "../types/api";

afterEach(() => {
  vi.unstubAllGlobals();
  localStorage.clear();
});

function renderReview(run: RunDetail) {
  const mock = installFetchMock([
    {
      match: /\/api\/runs\/run123\/review-actions$/,
      method: "POST",
      respond: (_url, init) => {
        const body = JSON.parse(String(init?.body)) as { action: string };
        return {
          body: {
            human_review_status: "in_review",
            review_actions: [
              {
                action: body.action,
                actor: "pat",
                note: null,
                finding_id: null,
                created_at: "2026-06-12T10:00:00",
              },
            ],
          },
        };
      },
    },
    {
      match: /\/api\/runs\/run123\/audit$/,
      respond: () => ({ body: { events: [] } }),
    },
    {
      match: /\/api\/runs\/run123$/,
      respond: () => ({ body: run }),
    },
  ]);
  render(
    <MemoryRouter initialEntries={["/runs/run123"]}>
      <ToastProvider>
        <Routes>
          <Route path="/runs/:runId" element={<ReviewRunPage />} />
        </Routes>
      </ToastProvider>
    </MemoryRouter>,
  );
  return mock;
}

describe("Review Run page", () => {
  it("renders the summary strip, findings, AI container, validation and exports from RunDetail", async () => {
    renderReview(makeRunDetail());

    // Header + summary strip.
    await screen.findByRole("heading", { level: 1, name: "Duplicate payment review" });
    expect(screen.getByText("Items flagged: 1")).toBeInTheDocument();
    expect(screen.getByText("2 total checks results")).toBeInTheDocument();
    expect(screen.getByText("Not yet reviewed")).toBeInTheDocument();
    expect(screen.getByText("Export files: 3")).toBeInTheDocument();

    // Deterministic findings, severity-grouped, plain-language rule heading.
    expect(
      screen.getByRole("heading", { name: "What the checks found" }),
    ).toBeInTheDocument();
    expect(screen.getByText(/High \(1\)/)).toBeInTheDocument();
    expect(
      screen.getByText("Same invoice number billed twice", { exact: false }),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "INV-1042 from Cascade Paving appears on two invoices with the same amount.",
      ),
    ).toBeInTheDocument();

    // AI trust boundary with the binding label and provider line.
    const aiRegion = screen.getByRole("region", {
      name: "AI-drafted commentary. Draft written by AI. Verify before use.",
    });
    expect(
      within(aiRegion).getByText("Draft - written by AI, verify before use"),
    ).toBeInTheDocument();
    expect(
      within(aiRegion).getByText(/Generated by mock\/mock-model/),
    ).toBeInTheDocument();
    expect(within(aiRegion).getByText(/share invoice number INV-1042/)).toBeInTheDocument();

    // Validation: passed with warnings -> amber badge + warning list.
    expect(screen.getAllByText("Passed with warnings").length).toBeGreaterThan(0);
    expect(
      within(aiRegion).getByText(
        "One number claim could not be matched to a source column.",
      ),
    ).toBeInTheDocument();

    // Exports: review packet first with its chip; AI-draft chip on _draft.md.
    expect(screen.getByText("review_packet.md")).toBeInTheDocument();
    expect(screen.getByText("Complete review packet")).toBeInTheDocument();
    expect(screen.getByText("Contains AI draft")).toBeInTheDocument();
  });

  it("renders the plain note card instead of an AI container when ai is null", async () => {
    renderReview(makeRunDetail({ ai: null, validation: null }));

    await screen.findByRole("heading", { level: 1, name: "Duplicate payment review" });
    expect(
      screen.getByText("The AI was not asked to write anything for this run."),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("region", {
        name: "AI-drafted commentary. Draft written by AI. Verify before use.",
      }),
    ).not.toBeInTheDocument();
  });

  it("posts a review action and re-renders status from the response", async () => {
    const { calls } = renderReview(makeRunDetail());

    await screen.findByRole("heading", { level: 1, name: "Duplicate payment review" });
    fireEvent.click(screen.getByRole("button", { name: "Mark reviewed" }));

    await screen.findByText("In review");
    const post = calls.find((c) => c.url.endsWith("/review-actions"));
    expect(post).toBeDefined();
    const sent = JSON.parse(String(post?.init?.body)) as Record<string, unknown>;
    expect(sent.action).toBe("mark_reviewed");
    expect(sent.finding_id).toBeNull();
  });

  it("renders the failed_preflight layout with the red card and no AI container", async () => {
    renderReview(
      makeRunDetail({
        status: "failed_preflight",
        findings: [],
        ai: null,
        validation: null,
        preflight: {
          status: "fail",
          llm_allowed: false,
          files: [],
          findings: [
            {
              code: "missing_required_column",
              severity: "critical",
              message: "Your AP invoice file is missing an amount column.",
              affected_input: "ap_invoices",
              blocks_run: true,
            },
          ],
          supported_checks: [],
          next_steps: ["Add an amount column, then check again."],
          suggested_mappings: [],
        },
      }),
    );

    await screen.findByText("File check failed - nothing was run");
    expect(
      screen.getByText(
        "We did not run the workflow and the AI wrote nothing. The report below explains what to fix.",
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("button", { name: "Fix and run again" }),
    ).toBeInTheDocument();
    expect(
      screen.getByText("The AI was not asked to write anything for this run."),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("heading", { name: "What the checks found" }),
    ).not.toBeInTheDocument();
  });
});
